### ISSUE TITLE
Migrate certain deployments to statefulsets

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#4169]
# Details

**Describe the solution you'd like:**

Due to a couple issues explained below, I have decided to move from deployments to statefulsets for certain applications.

- On node lost rook-ceph will not reschedule pods using a RWO ceph-block volume, there is a feature request for this to be implemented but there hasn't been much movement on it. As it stands there's no benefits over deployments to statefulsets due to this rook issue. Pods will need manual intervention to move to another node when a node dies regardless.
- On bootstrap of the cluster and when containing all apps under a single fluxtomiztion the PVC will not be created due to the `ceph-block` storageclass not being created yet. `VolumeClaimTemplates` and using rook-ceph as a dependency on the helm releases should eventually reconcile successfully.
- Added bonus of `VolumeClaimTemplates` is that the PVC will not be deleted when using `helm uninstall`. But since I'm not using an existing claim, trying to link a new helm release to an existing PVC might not be possible.

Migrating the PVs should be as easy as using https://github.com/utkuozdemir/pv-migrate

**Comment by tyriis** [comment]
Does the `dry run` does not fail anyway when you reference `crds`/`resources` not yet created?

I personally hate the `statefulsets` pattern and try to avoid it whenever possible, as it is a pain to restore `pv`/`pvc` for a `statefulset`, maybe i miss something here :D.

**Comment by onedr0p** [comment]
I haven't tested out of dry run would net a success but I'm not confident since a PVC can't be created without the storage class, I never tested my theory but it would make sense that flux wouldn't be happy trying to create a pvc without a storage class present.

Restoring PVCs isn't any different than using a deployment. Scale the workload down, do work to the volume, scale the workload back up.

**Comment by tyriis** [comment]
@onedr0p then I miss maybe something, last time it created new `pvc` with new `pv` instead of using existing ones.

**Comment by onedr0p** [comment]
> @onedr0p then I miss maybe something, last time it created new `pvc` with new `pv` instead of using existing ones.

Nope, it uses the existing PVC built from the VCT. That's one of the appeals here is you don't need to define the PVC outside the helm release.

**Comment by tyriis** [comment]
> Nope, it uses the existing PVC built from the VCT. That's one of the appeals I find is you don't need to define the PVC outside the helm release to get around helm uninstall removing the PVC.

This is true, on the other side I would prefer a backup solution that try to restore on new `pv` based on an annotation.

**Comment by budimanjojo** [comment]
As somebody who's been using `sts` for a long time: https://github.com/budimanjojo/home-cluster/tree/main/cluster/core/default/redis. There are other things to note about `VolumeClaimTemplates`:
1. It will be created with `instance_id` at the end of the name, for example: `jellyfin-config-jellyfin-0`. I don't know how consistence this is, but you really need to make sure the `sts` will always be in one instance or you'll get a silently `jellyfin-config-jellyfin-1` PVC being created in the background. (it never happen to me though, but I can imagine somebody doing `kubectl scale sts jellyfin --replicas 2` for fun or debugging).
2. The last time I try, there's no support for "adding labels" from the `app-template` helm chart yet for `VolumeClaimTemplates`, that's why I'm using `existingClaim` now. That's needed if you want to f.e add labels like "backup/this/pvc=true". It's been a long time already though, and looks like `app-template` v1.0.0 had some major overhaul to `volume` values.

**Comment by onedr0p** [comment]
> 2. The last time I try, there's no support for "adding labels" from the `app-template` helm chart yet for `VolumeClaimTemplates`, that's why I'm using `existingClaim` now. That's needed if you want to f.e add labels like "backup/this/pvc=true" (cough PMB). It's been a long time already though, and looks like `app-template` v1.0.0 had some major overhaul to `volume` values so I don't know the current situation.

That was added and labels are now supported on VCTs in 1.0.0+
